# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /storage/local/data1/gartung/temp/clang_cms

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /storage/local/data1/gartung/temp/clang_cms

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /storage/local/data1/gartung/temp/clang_cms/CMakeFiles /storage/local/data1/gartung/temp/clang_cms/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /storage/local/data1/gartung/temp/clang_cms/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ClangCms

# Build rule for target.
ClangCms: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ClangCms
.PHONY : ClangCms

# fast build rule for target.
ClangCms/fast:
	$(MAKE) -f CMakeFiles/ClangCms.dir/build.make CMakeFiles/ClangCms.dir/build
.PHONY : ClangCms/fast

src/ClangCmsCheckerPluginRegister.o: src/ClangCmsCheckerPluginRegister.cpp.o
.PHONY : src/ClangCmsCheckerPluginRegister.o

# target to build an object file
src/ClangCmsCheckerPluginRegister.cpp.o:
	$(MAKE) -f CMakeFiles/ClangCms.dir/build.make CMakeFiles/ClangCms.dir/src/ClangCmsCheckerPluginRegister.cpp.o
.PHONY : src/ClangCmsCheckerPluginRegister.cpp.o

src/ClangCmsCheckerPluginRegister.i: src/ClangCmsCheckerPluginRegister.cpp.i
.PHONY : src/ClangCmsCheckerPluginRegister.i

# target to preprocess a source file
src/ClangCmsCheckerPluginRegister.cpp.i:
	$(MAKE) -f CMakeFiles/ClangCms.dir/build.make CMakeFiles/ClangCms.dir/src/ClangCmsCheckerPluginRegister.cpp.i
.PHONY : src/ClangCmsCheckerPluginRegister.cpp.i

src/ClangCmsCheckerPluginRegister.s: src/ClangCmsCheckerPluginRegister.cpp.s
.PHONY : src/ClangCmsCheckerPluginRegister.s

# target to generate assembly for a file
src/ClangCmsCheckerPluginRegister.cpp.s:
	$(MAKE) -f CMakeFiles/ClangCms.dir/build.make CMakeFiles/ClangCms.dir/src/ClangCmsCheckerPluginRegister.cpp.s
.PHONY : src/ClangCmsCheckerPluginRegister.cpp.s

src/CmsException.o: src/CmsException.cpp.o
.PHONY : src/CmsException.o

# target to build an object file
src/CmsException.cpp.o:
	$(MAKE) -f CMakeFiles/ClangCms.dir/build.make CMakeFiles/ClangCms.dir/src/CmsException.cpp.o
.PHONY : src/CmsException.cpp.o

src/CmsException.i: src/CmsException.cpp.i
.PHONY : src/CmsException.i

# target to preprocess a source file
src/CmsException.cpp.i:
	$(MAKE) -f CMakeFiles/ClangCms.dir/build.make CMakeFiles/ClangCms.dir/src/CmsException.cpp.i
.PHONY : src/CmsException.cpp.i

src/CmsException.s: src/CmsException.cpp.s
.PHONY : src/CmsException.s

# target to generate assembly for a file
src/CmsException.cpp.s:
	$(MAKE) -f CMakeFiles/ClangCms.dir/build.make CMakeFiles/ClangCms.dir/src/CmsException.cpp.s
.PHONY : src/CmsException.cpp.s

src/ConstCastAwayChecker.o: src/ConstCastAwayChecker.cpp.o
.PHONY : src/ConstCastAwayChecker.o

# target to build an object file
src/ConstCastAwayChecker.cpp.o:
	$(MAKE) -f CMakeFiles/ClangCms.dir/build.make CMakeFiles/ClangCms.dir/src/ConstCastAwayChecker.cpp.o
.PHONY : src/ConstCastAwayChecker.cpp.o

src/ConstCastAwayChecker.i: src/ConstCastAwayChecker.cpp.i
.PHONY : src/ConstCastAwayChecker.i

# target to preprocess a source file
src/ConstCastAwayChecker.cpp.i:
	$(MAKE) -f CMakeFiles/ClangCms.dir/build.make CMakeFiles/ClangCms.dir/src/ConstCastAwayChecker.cpp.i
.PHONY : src/ConstCastAwayChecker.cpp.i

src/ConstCastAwayChecker.s: src/ConstCastAwayChecker.cpp.s
.PHONY : src/ConstCastAwayChecker.s

# target to generate assembly for a file
src/ConstCastAwayChecker.cpp.s:
	$(MAKE) -f CMakeFiles/ClangCms.dir/build.make CMakeFiles/ClangCms.dir/src/ConstCastAwayChecker.cpp.s
.PHONY : src/ConstCastAwayChecker.cpp.s

src/ConstCastChecker.o: src/ConstCastChecker.cpp.o
.PHONY : src/ConstCastChecker.o

# target to build an object file
src/ConstCastChecker.cpp.o:
	$(MAKE) -f CMakeFiles/ClangCms.dir/build.make CMakeFiles/ClangCms.dir/src/ConstCastChecker.cpp.o
.PHONY : src/ConstCastChecker.cpp.o

src/ConstCastChecker.i: src/ConstCastChecker.cpp.i
.PHONY : src/ConstCastChecker.i

# target to preprocess a source file
src/ConstCastChecker.cpp.i:
	$(MAKE) -f CMakeFiles/ClangCms.dir/build.make CMakeFiles/ClangCms.dir/src/ConstCastChecker.cpp.i
.PHONY : src/ConstCastChecker.cpp.i

src/ConstCastChecker.s: src/ConstCastChecker.cpp.s
.PHONY : src/ConstCastChecker.s

# target to generate assembly for a file
src/ConstCastChecker.cpp.s:
	$(MAKE) -f CMakeFiles/ClangCms.dir/build.make CMakeFiles/ClangCms.dir/src/ConstCastChecker.cpp.s
.PHONY : src/ConstCastChecker.cpp.s

src/GlobalStaticChecker.o: src/GlobalStaticChecker.cpp.o
.PHONY : src/GlobalStaticChecker.o

# target to build an object file
src/GlobalStaticChecker.cpp.o:
	$(MAKE) -f CMakeFiles/ClangCms.dir/build.make CMakeFiles/ClangCms.dir/src/GlobalStaticChecker.cpp.o
.PHONY : src/GlobalStaticChecker.cpp.o

src/GlobalStaticChecker.i: src/GlobalStaticChecker.cpp.i
.PHONY : src/GlobalStaticChecker.i

# target to preprocess a source file
src/GlobalStaticChecker.cpp.i:
	$(MAKE) -f CMakeFiles/ClangCms.dir/build.make CMakeFiles/ClangCms.dir/src/GlobalStaticChecker.cpp.i
.PHONY : src/GlobalStaticChecker.cpp.i

src/GlobalStaticChecker.s: src/GlobalStaticChecker.cpp.s
.PHONY : src/GlobalStaticChecker.s

# target to generate assembly for a file
src/GlobalStaticChecker.cpp.s:
	$(MAKE) -f CMakeFiles/ClangCms.dir/build.make CMakeFiles/ClangCms.dir/src/GlobalStaticChecker.cpp.s
.PHONY : src/GlobalStaticChecker.cpp.s

src/MutableMemberChecker.o: src/MutableMemberChecker.cpp.o
.PHONY : src/MutableMemberChecker.o

# target to build an object file
src/MutableMemberChecker.cpp.o:
	$(MAKE) -f CMakeFiles/ClangCms.dir/build.make CMakeFiles/ClangCms.dir/src/MutableMemberChecker.cpp.o
.PHONY : src/MutableMemberChecker.cpp.o

src/MutableMemberChecker.i: src/MutableMemberChecker.cpp.i
.PHONY : src/MutableMemberChecker.i

# target to preprocess a source file
src/MutableMemberChecker.cpp.i:
	$(MAKE) -f CMakeFiles/ClangCms.dir/build.make CMakeFiles/ClangCms.dir/src/MutableMemberChecker.cpp.i
.PHONY : src/MutableMemberChecker.cpp.i

src/MutableMemberChecker.s: src/MutableMemberChecker.cpp.s
.PHONY : src/MutableMemberChecker.s

# target to generate assembly for a file
src/MutableMemberChecker.cpp.s:
	$(MAKE) -f CMakeFiles/ClangCms.dir/build.make CMakeFiles/ClangCms.dir/src/MutableMemberChecker.cpp.s
.PHONY : src/MutableMemberChecker.cpp.s

src/StaticLocalChecker.o: src/StaticLocalChecker.cpp.o
.PHONY : src/StaticLocalChecker.o

# target to build an object file
src/StaticLocalChecker.cpp.o:
	$(MAKE) -f CMakeFiles/ClangCms.dir/build.make CMakeFiles/ClangCms.dir/src/StaticLocalChecker.cpp.o
.PHONY : src/StaticLocalChecker.cpp.o

src/StaticLocalChecker.i: src/StaticLocalChecker.cpp.i
.PHONY : src/StaticLocalChecker.i

# target to preprocess a source file
src/StaticLocalChecker.cpp.i:
	$(MAKE) -f CMakeFiles/ClangCms.dir/build.make CMakeFiles/ClangCms.dir/src/StaticLocalChecker.cpp.i
.PHONY : src/StaticLocalChecker.cpp.i

src/StaticLocalChecker.s: src/StaticLocalChecker.cpp.s
.PHONY : src/StaticLocalChecker.s

# target to generate assembly for a file
src/StaticLocalChecker.cpp.s:
	$(MAKE) -f CMakeFiles/ClangCms.dir/build.make CMakeFiles/ClangCms.dir/src/StaticLocalChecker.cpp.s
.PHONY : src/StaticLocalChecker.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... ClangCms"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/ClangCmsCheckerPluginRegister.o"
	@echo "... src/ClangCmsCheckerPluginRegister.i"
	@echo "... src/ClangCmsCheckerPluginRegister.s"
	@echo "... src/CmsException.o"
	@echo "... src/CmsException.i"
	@echo "... src/CmsException.s"
	@echo "... src/ConstCastAwayChecker.o"
	@echo "... src/ConstCastAwayChecker.i"
	@echo "... src/ConstCastAwayChecker.s"
	@echo "... src/ConstCastChecker.o"
	@echo "... src/ConstCastChecker.i"
	@echo "... src/ConstCastChecker.s"
	@echo "... src/GlobalStaticChecker.o"
	@echo "... src/GlobalStaticChecker.i"
	@echo "... src/GlobalStaticChecker.s"
	@echo "... src/MutableMemberChecker.o"
	@echo "... src/MutableMemberChecker.i"
	@echo "... src/MutableMemberChecker.s"
	@echo "... src/StaticLocalChecker.o"
	@echo "... src/StaticLocalChecker.i"
	@echo "... src/StaticLocalChecker.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

